#!/usr/bin/env python3
# -*- coding:utf-8 -*-

#通用错误编码 1~ 100
EC_VALUE = 1            #数值错误
EC_TIME_UNDUE = 2       #时间未到
EC_TIMEOUT = 3          #超时
EC_NOLEVEL = 4          #等级未到
EC_NOVIP = 5            #不是vip用户
EC_COST_ERR = 6         #扣费失败
EC_NO_RIGHT = 7         #无此权限
EC_HANDLED = 8          #操作已处理
EC_PLAYER_EMPTY = 9     #该玩家已经不存在
EC_NAME_REPEAT = 10     #重名
EC_NOFOUND = 11         #找不到
EC_PAY_FAIL = 12        #支付失败
EC_USER_MAX = 13        #达到最大玩家数
EC_NORES = 14           #无资源
EC_TIMES_FULL = 15      #使用次数已到达上限
EC_CLOSE = 16           #功能未开放
EC_PLAYER_OFFLINE = 17  #玩家不在线
EC_NET_ERR = 18         #网络连接错误
EC_LOGIN_ERR = 19       #登陆错误
EC_FORBID_STRING = 20   #敏感词
EC_PARAMS_ERR = 21 #参数错误
EC_NOT_ENOUGH = 22 #数量不够
EC_CREATE_ERR = 23 #创建失败
EC_PASSWORD_ERR = 24 #密码错误
EC_NOT_GM = 25 #没有GM权限
EC_NOT_GM_CMD = 26 #没有GM指令
EC_EXEC_GM_CMD = 27 #执行GM指令出错
EC_MAX_LEVEL = 28 #等级已满
EC_SAME_ACCOUNT = 29 #账号已注册
EC_TOKEN_ERR = 30 #令牌错误
EC_NOT_OPEN = 31 #活动未开启
EC_ALREADY_REWARD = 32 #已经领奖
EC_NOT_ABLE = 33 #不可用
EC_EXHAUSTED = 34 #次数用尽
EC_ALREADY_GONG = 35 #已经消失
EC_NO_FINISH = 36 #未完成
EC_ALREADY_FINISH = 37 #已完成
EC_NO_START = 38 #未开始
EC_FREE_EXHAUSTED = 39 #免费次数用尽


#通用错误编码 1~ 100

#自定义错误码 101 ~~~~~~~~~~~~~~~~~~~
EC_TOTEM_HAS_ACT = 101 #图腾已激活
EC_TOTEM_ACT_NOT_ENOUGH = 102 #图腾激活材料不足
EC_NOT_FIND_TOTEM = 103 #没有找到技能
EC_TOTEM_UPGRADE_NOT_ENOUGH = 104 #图腾升级材料不足
EC_TOTEM_NOT_NEED_TP = 105 #图腾不需要突破
EC_TOTEM_CAN_NOT_TP = 106 #图腾经验不足，不能突破
EC_PET_CAN_NOT_COST_WEAR = 107 #宠物有穿戴物品，不可消耗
EC_PET_CAN_NOT_COST_FIGHT = 108 #宠物已出战，不可消耗
EC_FRIEND_ALEADY_FOLLOW = 109 #已关注对方
EC_FRIEND_FOLLOW_LIMIT = 110 #已达关注上限
EC_FRIEND_ALEADY_BLACK = 111 #已在黑名单
EC_FRIEND_BLACK_LIMIT = 112 #已达黑名单上限
EC_FRIEND_ALEADY_PRESENT = 113 #已赠送过
EC_FRIEND_NOT_FOLLOW = 114 # 没有关注
EC_FRIEND_ALEADY_RECEIVE = 115 #已接收过
EC_FRIEND_NOT_IN_RECEIVE = 116 #不在可接收列表
EC_FRIEND_RECEIVE_LIMIT = 117 #已达接收上限
EC_FRIEND_FAN_LIMIT = 118 #已达粉丝上限
EC_PET_NOT_ACT = 119 #宠物未激活
EC_PET_UPGRADE_NOT_ENOUGH = 120 #宠物升级材料不足
EC_PET_EVOLVE_NOT_ENOUGH = 121 #宠物进化材料不足
EC_PET_MUTEX_LIMIT = 122 #宠物互斥
EC_MAIL_ALERAY_GET_ATTACHMENT = 123 #邮件已领取
EC_MARRY_ALREAY_MARRY = 124 # 已婚
EC_MARRY_NOT_ONLINE = 125   # 对方不在线
EC_MARRY_NOT_ENOUGH = 126   # 费用不足
EC_MARRY_NOT_MARRY = 127    # 未婚
EC_HOUSE_NO_HOUSE = 128     # 没房子
EC_HOUSE_MAX_LEVEL = 129    # 已达最高阶
EC_MARRY_ALEARY_TODAY = 130 # 今日已结过婚
EC_MARRY_NOT_EN = 131    # 未婚亲密度能量不足
EC_MARRY_NOT_TODAY_LIMIT = 132    # 未婚亲密度今日到达上限
EC_HOUSE_UPGRADE_NOT_ENOUGH = 133  # 升阶材料不足
EC_GRBOSS_HAS_KILL = 134 #个人boss已被击杀
EC_GRBOSS_LV_NOT_ENOUGH = 135 #个人boss等级不够
EC_GRBOSS_NUM_NOT_ENOUGH = 136 #个人boss挑战次数不足
EC_QMBOSS_BUY_CNT_LIMIT = 137 #全民boss购买次数已达上限
EC_QMBOSS_BUY_NOT_ENOUGH = 138 #全民boss购买材料不足
EC_QMBOSS_NUM_FULL = 139 #全民boss挑战次数已满
EC_QMBOSS_NOT_FIND = 140 #全民boss不存在
EC_QMBOSS_HAS_KILL = 141 #全民boss已被击杀
EC_QMBOSS_ALIVE = 142 #全民boss存活
EC_QMBOSS_REBORN_LIMIT = 143 #全民boss复活限制
EC_YWBOSS_LV_LIMIT = 144 #野外boss等级不够
EC_YWBOSS_STATUS_ERR = 145 #野外boss状态错误
EC_YWBOSS_FIGHT_NOT_ENOUGH = 146 #野外boss挑战材料不足
EC_QMBOSS_TZ_NOT_ENOUGH = 147 #全民boss挑战次数不足
EC_YWBOSS_CD = 148 #野外boss挑战CD
EC_SSJBOSS_HAS_KILLED = 149 #生死劫boss已被击杀
EC_GRBOSS_NOT_KILLED = 150 #个人boss未首通
EC_SSJBOSS_BARR_LIMIT = 151 #生死劫boss前置关卡未通关
EC_YWBOSS_HAS_OCCUPY = 152 #已有占领的野外boss
EC_QMBOSS_REBORN_NOT_ENOUGH = 153 #全民boss复活材料不足
EC_INIT_BARR_FAIL = 154 #副本初始化失败
EC_GR_BOSS_SWEEP_VIP_LIMIT = 155 #个人boss一键扫荡vip等级不足
EC_CHENGHAO_HAS_ACT = 156 #称号激活
EC_CHENGHAO_ACT_NOT_ENOUGH = 157 #称号激活材料不足
EC_CHENGHAO_NOT_FIND_TOTEM = 158 #没有找到称号
EC_CHENGHAO_HASNOT_ACT = 159 #称号未激活
EC_CHENGHAO_UP_NOT_ENOUGH = 160 #称号升级材料不足
EC_MYHEAD_HAS_ACT = 161 #头像激活
EC_MYHEAD_ACT_NOT_ENOUGH = 162 #头像激活材料不足
EC_MYHEAD_NOT_FIND_TOTEM = 163 #头像没有找到时装
EC_MYHEAD_HASNOT_ACT = 164 #头像未激活
EC_PET_WASH_POS_ERROR = 165 #宠物洗练位置错误
EC_PET_WASH_NOT_ENOUGH = 166 #宠物洗练材料不足
EC_PET_WASH_ALL_LOCK = 167 #宠物洗练技能全锁定
EC_PET_EVOLVE_EAT_SELF = 168 #不可以吃自己
EC_BAG_SIZE_MAX = 169 #背包扩容已达上限
EC_TOTEM_NEED_TP = 170 #图腾需要突破

EC_ENCOUNTER_FIGHT_LIMIT = 265 # 遭遇战条件不足
EC_ENCOUNTER_FIGHT_HAS_FINISH = 266 #遭遇战已经通关
EC_ENCOUNTER_FIGHT_NOT_FINISH = 278 #遭遇战未完成
EC_ENTER_MAP_LIMIT = 264 #进入地图条件不足

EC_DAOGUAN_FIGHT_ID_ERROR = 267 #道馆挑战副本错误
EC_DAOGUAN_FIGHT_AREA_ERROR = 268 #道馆挑战区域错误
EC_DAOGUAN_NOT_FIND = 269 #道馆不存在
EC_DAOGUAN_FIGHT_LIMIT = 270 #道馆挑战条件不足
EC_DAOGUAN_FIGHT_NUM_LIMIT = 271 #道馆挑战次数不足
EC_DAOGUAN_HAS_FIRST_FINISH = 272 #道馆已首通
EC_DAOGUAN_BARR_HAS_FINISH = 273 #道馆副本已挑战
EC_DAOGUAN_HAS_SWEEP = 274 #道馆今日已扫荡
EC_DAOGUAN_SWEEP_LIMIT = 275 #道馆扫荡条件不足
EC_DAOGUAN_VIP_BUY_LIMIT = 276 #道馆每日挑战次数购买上限
EC_DAOGUAN_VIP_BUY_NOT_ENOUGH = 277 #道馆购买挑战次数钻石不足

EC_ZHUDAOXUNLI_NOTOPEN = 1140 # 诸岛巡礼-未开启
EC_ZHUDAOXUNLI_NONEED = 1141 # 诸岛巡礼-分数不够
EC_ZHUDAOXUNLI_ALREADY = 1142 # 诸岛巡礼-已经领取
EC_ZHUDAOXUNLI_NOVIP = 1143 # 诸岛巡礼-不是VIP


EC_DAYLY_PVP_NOT_DATA = 281 #日常挑战角色数据不存在
EC_DAYLY_PVP_CHALLENGE_NOT_ENOUGH = 282 #日常挑战次数不足
EC_DAYLY_PVP_REWARD_HAS_GET = 283 #日常挑战连胜奖励已领取
EC_DAYLY_PVP_WIN_NOT_ENOUGH = 284 #日常挑战连胜次数不足
EC_DAYLY_PVP_BUY_CHALLENGE_NUM_LIMIT = 285 # 日常挑战购买挑战次数已打上限
EC_DAYLY_PVP_BUY_CHALLENGE_NOT_ENOUGH = 286 # 日常挑战购买挑战次数钻石不足
EC_DAYLY_PVP_REFRESH_NOT_ENOUGH = 286 # 日常挑战更换对手钻石不足
EC_DAYLY_PVP_NOT_RANK_DATA = 287 # 日常挑战无排行榜数据
EC_DAYLY_PVP_WEEK_RANK_REWARD_HAS_GET = 288 # 日常挑战周排行榜奖励已领取
EC_DAYLY_PVP_CHALLENGE_HAS_WIN = 289 # 日常挑战已击败对手
EC_DAYLY_PVP_HAS_REVENGE = 290 # 日常挑战已复仇对手
EC_HETI_MAX = 518 #合体 超过次数限制
EC_HETI_TIMEOUT = 519 #合体 超过时间
EC_HETI_BUYMAX = 534 #合体 超过购买次数
EC_HETI_NUMZERO = 535 #合体 目前不能购买
EC_HETI_NOFOUND = 580 #合体 未找到该物体

EC_GETD_GROUPKEYFAIL = 327 #获取获取房间Group失败
EC_GETD_RPC_ROOM_FAIL = 328 #获取房间RPCPROXY失败
EC_CALL_RPC_ROOM_FAIL = 329 #房间RPC失败
EC_GETD_LOGIC_PROXY_ERR = 330 #获取逻辑服RPCPROXY失败
EC_CALL_LOGIC_PROXY_ERR = 331 #逻辑服RPC失败

EC_GONGCHENG_NOTFOUNDDATA = 560 #攻城-没找到玩家数据
EC_GONGCHENG_NOTFOUNDPET = 561 #攻城-没找到宠物
EC_GONGCHENG_NOTFOUNDTEAM = 562 #攻城-没找到队伍
EC_GONGCHENG_NOTFOUNDCITY = 563 #攻城-没找到城市
EC_GONGCHENG_TEAMISSEND = 564 #攻城-队伍已经派出
EC_GONGCHENG_PEIHASTEAM = 565 #攻城-宠物已经编队
EC_GONGCHENG_PETISLOCK = 566 #攻城-宠物已锁定
EC_GONGCHENG_ERR = 567 #攻城-跨服出错
EC_GONGCHENG_NOGIVEUP = 568 #攻城-不能放弃城市
EC_GONGCHENG_NOFOUNDLOG = 569 #攻城-找不到战报
EC_GONGCHENG_BIGCITYLOCK = 570 #攻城-不能攻打。其他公会正在攻打
EC_GONGCHENG_NOTFOUNDPLAYER = 571 #攻城-找不到玩家
EC_GONGCHENG_NEEDWAR = 572 #攻城-不能攻打。需要宣战
EC_GONGCHENG_INWARTIME = 573 #攻城-正在宣战中
EC_GONGCHENG_INWARING = 574 #攻城-正在交战中
EC_GONGCHENG_GIVEERRBYWAR = 575 #攻城-宣战中不能放弃城市
EC_GONG_CHENG_TIME_LIMIT = 910 #全民攻城 非活动时间
EC_GONG_CHENG_LOGIN_REWARD_HAS_GET = 911 #全民攻城 登陆奖励已领取
EC_GONG_CHENG_REWARD_LIMIT = 912 #全民攻城 礼包已达购买上限
EC_GONG_CHENG_REWARD_CHARGE = 913 #全民攻城 直购礼包类型
EC_GONG_CHENG_REWARD_NOT_ENOUGH = 914 #全民攻城 购买条件不足
EC_GONG_CHENG_TASK_NOT_FINISH = 915 #全民攻城 任务未完成
EC_GONG_CHENG_TASK_REWARD_HAS_GET = 916 #全民攻城 任务奖励已领取
EC_GONG_CHENG_SHOP_LIMIT = 917 #全民攻城 商品已达购买上限
EC_GONG_CHENG_SHOP_NOT_ENOUGH = 918 #全民攻城 商品购买条件不足
EC_GONG_CHENG_LOGIN_REWARD_NOT_ENOUGH = 919 #全民攻城 登陆天数不足
EC_GONGCHENG_QUANMING_NORANK = 920 #全民攻城排行，没有排行
EC_GONGCHENG_QUANMING_ALREADY = 921 #全民攻城排行，已经领奖
EC_GONGCHENG_QUANMING_NOOPEN = 922 #全民攻城排行，未开启


EC_NOT_FOUND_GUILD = 146 #公会不存在
EC_GUILD_CREATE_LV_ERR = 147 #公会创建等级错误
EC_GUILD_NAME_REPET = 148 #公会名称重复
EC_GUILD_CREATE_VIP_LIMIT = 149 #公会创建vip限制
EC_GUILD_CREATE_NOT_ENOUGH = 150 #公会创建材料不足
EC_GUILD_CREATE_FAIL = 151 #创建公会失败
EC_GUILD_HAS_JOIN = 152 #已经加入帮会
EC_NO_GUILD = 153 #没有加入公会
EC_GUILD_OPER_ERR = 154 #帮会操作错误

EC_GUILD_HAS_APPLY = 164 #已申请加入帮会
EC_GUILD_NOT_APPLY = 165 #没有申请加入帮会
EC_GUILD_MEMBER_MAX = 166 #帮会人员已满
EC_GUILD_OPER_LIMIT = 167 #帮会权限不足
EC_GUILD_MASTER_EXIT = 168 #帮主需要让位才出可以退出帮会
EC_GUILD_TODAY_HAS_SX = 169 #今日已上香
EC_GUILD_SX_NOT_ENOUGH = 170 #帮会上香材料不足
EC_GUILD_SX_MAX_NUM = 171 #帮会上香次数已满
EC_GUILD_DEPUTY_MAX_NUM = 172 #副帮主人数已达上限
EC_GUILD_SX_REWARD_HAS_GET = 173 #帮会香火值奖励已领取
EC_GUILD_SX_REWARD_NOT_ENOUGH = 174 #帮会香火值不足
EC_GUILD_TASK_NOT_FOUND = 175 #没有帮会任务
EC_GUILD_TASK_FINISH_NOT_ENOUGH = 176 #帮会任务一键完成材料不足
EC_GUILD_TASK_RESET_MAX_NUM = 177 #帮会任务重置次数已达上限
EC_GUILD_TASK_RESET_NOT_ENOUGH = 178 #帮会任务重置材料不足
EC_GUILD_ACT_UPGRADE_EXP_NOT_ENOUGH = 179 #帮会活跃等级提升经验不足
EC_GUILD_DONATE_NOT_ENOUGH = 180 #帮会捐献材料不足
EC_GUILD_SKILL_UP_LIMIT = 181 #帮会技能升级已达上限
EC_GUILD_SKILL_UP_NOT_ENOUGH = 182  #帮会技能升级材料不足
EC_GUILD_EXCHANGE_NOT_FOUND = 183 #帮会兑换id不存在
EC_GUILD_EXCHANGE_NOT_ENOUGH = 184 #帮会兑换材料不足
EC_GUILD_EXCHANGE_HAS_BUY = 185 #帮会兑换id已兑换
EC_GUILD_TASK_HAS_FINISH = 187 #帮会任务已完成
EC_GUILD_EXCHANGE_REFESH_MAX = 188 #帮会刷新次数已满
EC_GUILD_EXCHANGE_REFE_NOT_ENOUGH = 189 #帮会兑换刷新材料不足
EC_GUILD_BARR_LIMIT = 190 #帮会副本未开启
EC_GUILD_TASK_REWARD_HAS_GET = 193 # 帮会任务奖励已领取
EC_GUILD_ACT_TASK_NOT_FIND = 200 #帮会活跃任务未找到
EC_GUILD_ACT_TASK_NOT_FINISH = 201 #帮会活跃任务未完成
EC_GUILD_ACT_TASK_REWARD_HAS_GET = 202 #帮会活跃任务奖励已领取
EC_GUILD_EX_FREE_REF_TIME_ERR = 204 #帮会兑换免费刷新时间未到


EC_HUSONG_TIME_NO_ZERO = 332 #押镖-护送-护送中或未领奖
EC_HUSONG_NUM_USEUP = 333 #押镖-护送-次数用尽
EC_FASTCOMPLETE_TIME_BAD = 334 #押镖-快速完成-不能快速完成已完成押镖
EC_HUSONGREWARD_TIMENOABLE = 335 #押镖-护送奖励-时间未到
EC_HUSONGREWARD_NOSTART = 336 #押镖-护送奖励-未开始
EC_ROBHUSONG_USEUP = 337 #押镖-劫镖-劫镖次数用尽
EC_ROBHUSONG_LIMIT = 338 #押镖-劫镖-被劫人达到上限制
EC_ROBHUSONG_ALREADY = 339 #押镖-劫镖-已经接过
EC_FLASHCAR_TIMENOABLE = 340 #押镖-刷车-不可刷车
EC_REVENGEHUSONG_NOIN = 341 #押镖-复仇-不在历史记录
EC_REVENGEHUSONG_NOTYPE = 342 #押镖-复仇-不是可复仇类型
EC_HUSONG_NOFOUNDONE = 343 #押镖-找不到某人


EC_DIAOYU_CHANGEROOM_ERR = 420 #钓鱼换房失败
EC_DIAOYU_NOTOPEN = 421 #钓鱼——活动未开
EC_DIAOYU_NOFOUNDONE = 422 #钓鱼-找不到某人
EC_DIAOYU_STATUSERR = 423 #钓鱼-改变状态失败
EC_DIAOYU_DIAOYUERR = 424 #钓鱼-钓鱼失败
EC_DIAOYU_DIAOYU_NOABLE = 425 #钓鱼-还不能钓鱼
EC_DIAOYU_ROB_USEUP = 426 #钓鱼-劫鱼-劫鱼次数用尽
EC_DIAOYU_ROB_LIMIT = 427 #钓鱼-劫鱼-对方不能再被抢了
EC_DIAOYU_NOFOUNDONEFISH = 428 #钓鱼-鱼被抢走了

#错误码 10001~~~~~~~~~~~~
EC_CODE_10001 = 10001 #xxxxxxxxxxxxxxxx
EC_CODE_10002 = 10002 #不能重复打boss
EC_CODE_10003 = 10003 #任务已接
EC_CODE_10004 = 10004 #已派遣
EC_CODE_10005 = 10005 #宠物id不匹配
EC_CODE_10006 = 10006 #宠物属性不匹配
EC_CODE_10007 = 10007 #宠物星级不匹配






















