#!/usr/bin/env python3
# -*- coding:utf-8 -*-

#============================== 系统类事件 全局Game =========================================
MSG_LOGIN = 'MSG_LOGIN'
MSG_LOGOUT = 'MSG_LOGOUT'

MSG_WEE_HOURS = 'MSG_WEE_HOURS' #凌晨定时事件
MSG_HALF_HOURS = 'MSG_HALF_HOURS' #半小时定时事件
MSG_TWO_HOURS = "MSG_TWO_HOURS" #两小时定时事件

MSG_RANK = "MSG_RANK"

MSG_EIGHT_FIFTY_FIVE_PM = "MSG_EIGHT_FIFTY_FIVE_PM" # 每晚8点55定时事件
MSG_NINE_PM = "MSG_NINE_PM" # 每晚9点定时事件
MSG_NINE_HALF_PM = "MSG_NINE_HALF_PM" # 每晚9点半定时事件
MSG_TEN_PM = "MSG_TEN_PM" # 每晚10点定时事件

#============================== 战斗事件 Fight =========================================
MSG_FIGHT_SPEED_CHANGE = "MSG_FIGHT_SPEED_CHANGE" #速度发生变化
MSG_FIGHT_WAVE_INIT = "MSG_FIGHT_WAVE_INIT" #战斗初始化
MSG_FIGHT_BEFORE_ROUND_1 = "MSG_FIGHT_BEFORE_ROUND_1" #回合启动阶段--1
MSG_FIGHT_BEFORE_ROUND_2 = "MSG_FIGHT_BEFORE_ROUND_2" #回合启动阶段--2
MSG_FIGHT_DO_ROUND_BF_1 = "MSG_FIGHT_DO_ROUND_BF_1" #行动启动阶段--1
MSG_FIGHT_DO_ROUND_1 = "MSG_FIGHT_DO_ROUND_1" #行动执行阶段--1
MSG_FIGHT_DO_ROUND_END_1 = "MSG_FIGHT_DO_ROUND_END_1" #行动结束阶段--1


MSG_FIGHT_WILL_DEAD = "MSG_FIGHT_WILL_DEAD" #濒死流程




#===========================  角色类事件 player =============================================
MSG_ENTER_GAME = 'MSG_ENTER_GAME' #进入游戏
MSG_ROLE_LEVEL_UPGRADE = "MSG_ROLE_LEVEL_UPGRADE" #角色升级
MSG_ROLE_XLV_UPGRADE = "MSG_ROLE_XLV_UPGRADE" #角色升级
MSG_ROLE_VIPLV_UPGRADE = "MSG_ROLE_VIPLV_UPGRADE" #VIP升级
MSG_FA_CHANGE = "MSG_FA_CHANGE" #战力变化
MSG_PET_ALBUMNUM_CHANGE = "MSG_PET_ALBUMNUM_CHANGE" #宠物图鉴数量变化
MSG_PET_ACTIVATE = "MSG_PET_ACTIVATE" #宠物激活
MSG_TOTEM_ACT = "MSG_TOTEM_ACT" #图腾激活
MSG_ROLE_ATTR_CHANGE = "MSG_ROLE_ATTR_CHANGE" #角色属性发生变化
MSG_TOTEM_UPGRADE = "MSG_TOTEM_UPGRADE" #图腾升级
MSG_ADD_FOLLOW_FRIEND = "MSG_ADD_FOLLOW_FRIEND" #关注好友
MSG_FRIEND_SEND = "MSG_FRIEND_SEND" #好友赠送
MSG_PET_UPGRADE = "MSG_PET_UPGRADE" #宠物升级
MSG_PET_EVOLVE = "MSG_PET_EVOLVE" #宠物进化
MSG_JIEHUN_AGREE = "MSG_JIEHUN_AGREE" #结婚同意
MSG_JOIN_EXAM = "MSG_JOIN_EXAM" #参与答题活动
MSG_KILL_YW_BOSS = "MSG_KILL_YW_BOSS" #击杀野外boss
MSG_GR_BOSS = "MSG_GR_BOSS" #个人boss
MSG_QM_BOSS = "MSG_QM_BOSS" #全民boss
MSG_SSJ_BOSS = "MSG_SSJ_BOSS" #参与大师塔（生死劫）
MSG_CHENGHAO_ACT = "MSG_CHENGHAO_ACT" #称号激活
MSG_PET_SKILL_WASH = "MSG_PET_SKILL_WASH" #宠物技能洗练
MSG_CHANGE_BATTLE_ARRAY = "MSG_CHANGE_BATTLE_ARRAY" #出战阵型变更
MSG_PET_CHANGE = "MSG_PET_CHANGE" #宠物数量变更
MSG_MORMAL_SCENE_FIGHT = "MSG_MORMAL_SCENE_FIGHT" #普通战斗
MSG_ENTER_MAP = "MSG_ENTER_MAP" #进入下一个地图
MSG_PASS_ENCOUNTER_FIGHT = "MSG_PASS_ENCOUNTER_FIGHT" #遭遇战
MSG_MINI_GAME_JOIN = "MSG_MINI_GAME_JOIN" #参与合体小游戏
MSG_MINI_GAME_UP_TO_STD = "MSG_MINI_GAME_UP_TO_STD" #合体小游戏分数达到n分



MSG_XIANSHITUISONGLIBAO_DAYLYPVP_F = "MSG_XIANSHITUISONGLIBAO_DAYLYPVP_F" #限时推送礼包 附近对手	战斗失败
MSG_DAYLY_PVP_FIGHT = "MSG_DAYLY_PVP_FIGHT" #日常抢夺
MSG_DAYLY_PVP_GET_REWARD = "MSG_DAYLY_PVP_GET_REWARD" #日常抢夺奖励领取
MSG_DAYLY_PVP_REVENGE = "MSG_DAYLY_PVP_REVENGE" #日常pvp复仇

MSG_GET_GONGCHENG_TASK_DATA = "MSG_GET_GONGCHENG_TASK_DATA" #获取攻城战任务数据
MSG_GET_GONGCHENG_ATK_WIN = "MSG_GET_GONGCHENG_ATK_WIN" #攻城战成功占领
MSG_GET_GONGCHENG_DEF_WIN = "MSG_GET_GONGCHENG_DEF_WIN" #攻城战成功防守


MSG_GUILD_BOSS_FIGHT = "MSG_GUILD_BOSS_FIGHT" #帮会boss
MSG_GUILD_EXCHANGE = "MSG_GUILD_EXCHANGE" #帮会收购
MSG_GUILD_SX = "MSG_GUILD_SX" #帮会上香
MSG_GUILD_BARR = "MSG_GUILD_BARR" #帮会副本
MSG_GUILD_SCENE_BARR = "MSG_GUILD_SCENE_BARR" #帮会小妖
MSG_GUILD_SCENE_CJ = "MSG_GUILD_SCENE_CJ" #帮会采集
MSG_GUILD_TODAY_ACTEXP_CHANGE = "MSG_GUILD_TODAY_ACTEXP_CHANGE" #帮会今日活跃变化
MSG_JOIN_GUILD = "MSG_JOIN_GUILD" #加入公会
MSG_GUILD_COLLECT = "MSG_GUILD_COLLECT" #帮会采集
MSG_GUILD_MONSTER_KILL = "MSG_GUILD_MONSTER_KILL" #帮会小怪击杀
MSG_KILL_GUILD_FB = "MSG_KILL_GUILD_FB" #成功挑战帮会副本
MSG_FIGHT_GUILD_FB = "MSG_FIGHT_GUILD_FB" #挑战帮会副本
MSG_GUILD_SKILL_UPGRADE = "MSG_GUILD_SKILL_UPGRADE" #公会技能提升
MSG_GET_GUILD_ACT_REWARD = "MSG_GET_GUILD_ACT_REWARD" #领取帮会活跃奖励
MSG_GUILD_WAR_SEND = "MSG_GUILD_WAR_SEND" #公会战派遣

MSG_XIANSHITUISONGLIBAO_DIAOYU_F = "MSG_XIANSHITUISONGLIBAO_DIAOYU_F" #限时推送礼包 钓鱼	战斗失败
MSG_JOIN_DIAOYU = "MSG_JOIN_DIAOYU" #参与跨服钓鱼